#!/bin/bash
#$1 is the list of all nodes[format:memphis,ucla,arizona...,uiuc], $2 is this node, $3 is the convergence time (ctime)

sleep "$3"

var1=true

IFS=',' read -ra ADDR <<< "$1"
for i in "${ADDR[@]}"; do
    contains=$(nfd-status -b | grep "/ndn/edu/$i")
    router=$(nfd-status -b | grep "/ndn/edu/%C1.Router/cs/$i")
    if [ "$i" != "$2" ]
    then
	if [ -z "$contains" ] || [ -z "$router" ]    #-z: string is emtpy
    	then
            var1=false
	    break
        fi
    fi
done

echo "$var1" > result

#for i in "${ADDR[@]}"; do
#    if [ "$i" != "$2" ]
#    then
#	ndnping -t -c 3 "/ndn/edu/$i" > "$i.ping"
#    fi
#done

